package qxEngineResponse

var WrongMessageEnUS = map[int32]string{
	QxEngineStatusContinue:                      "Continue",
	QxEngineStatusSwitchingProtocols:            "Switching Protocols",
	QxEngineStatusProcessing:                    "Processing",
	QxEngineStatusEarlyHints:                    "Early Hints",
	QxEngineStatusAccessTokenInvalid:            "accessToken invalid",
	QxEngineStatusAccessExpired:                 "accessToken expried",
	QxEngineStatusRefreshTokenInvalid:           "refreshToken invalid",
	QxEngineStatusRefreshTokenExpired:           "refreshToken expried",
	QxEngineStatusAccountNotFound:               "account not found",
	QxEngineStatusOK:                            "OK",
	QxEngineStatusCreated:                       "Created",
	QxEngineStatusAccepted:                      "Accepted",
	QxEngineStatusNonAuthoritativeInfo:          "Non-Authoritative Information",
	QxEngineStatusNoContent:                     "No Content",
	QxEngineStatusResetContents:                 "Reset Content",
	QxEngineStatusPartialContent:                "Partial Content",
	QxEngineStatusMultiStatus:                   "Multi-Status",
	QxEngineStatusAlreadyReported:               "Already Reported",
	QxEngineStatusIMUsed:                        "IM Used",
	QxEngineStatusNotTrustDevice:                "not trust device",
	QxEngineStatusAccountExists:                 "account already exists",
	QxEngineStatusMultipleChoices:               "Multiple Choices",
	QxEngineStatusMovedPermanently:              "Moved Permanently",
	QxEngineStatusFound:                         "Found",
	QxEngineStatusSeeOther:                      "See Other",
	QxEngineStatusNotModified:                   "Not Modified",
	QxEngineStatusUseProxy:                      "Use Proxy",
	QxEngineUnused:                              "Unused",
	QxEngineStatusTemporaryRedirect:             "Temporary Redirect",
	QxEngineStatusPermanentRedirect:             "Permanent Redirect",
	QxEngineStatusRedirectSuccess:               "redirect success",
	QxEngineStatusBadRequest:                    "Bad Request",
	QxEngineStatusUnauthorized:                  "Unauthorized",
	QxEngineStatusPaymentRequired:               "Payment Required",
	QxEngineStatusForbidden:                     "Forbidden",
	QxEngineStatusNotFound:                      "Not Found",
	QxEngineStatusMethodNotAllowed:              "Method Not Allowed",
	QxEngineStatusNotAcceptable:                 "Not Acceptable",
	QxEngineStatusProxyAuthRequired:             "Proxy Authentication Required",
	QxEngineStatusRequestTimeout:                "Request Timeout",
	QxEngineStatusConflict:                      "Conflict",
	QxEngineStatusGone:                          "Gone",
	QxEngineStatusLengthRequired:                "Length Required",
	QxEngineStatusPreconditionFailed:            "Precondition Failed",
	QxEngineStatusRequestEntityTooLarge:         "Request Entity Too Large",
	QxEngineStatusRequestURITooLong:             "Request URI Too Long",
	QxEngineStatusUnsupportedMediaType:          "Unsupported Media Type",
	QxEngineStatusRequestedRangeNotSatisfiable:  "Requested Range Not Satisfiable",
	QxEngineStatusExpectationFailed:             "Expectation Failed",
	QxEngineStatusTeapot:                        "I'm a teapot",
	QxEngineStatusMisdirectedRequest:            "Misdirected Request",
	QxEngineStatusUnprocessableEntity:           "Unprocessable Entity",
	QxEngineStatusLocked:                        "Locked",
	QxEngineStatusFailedDependency:              "Failed Dependency",
	QxEngineStatusTooEarly:                      "Too Early",
	QxEngineStatusUpgradeRequired:               "Upgrade Required",
	QxEngineStatusPreconditionRequired:          "Precondition Required",
	QxEngineStatusTooManyRequests:               "Too Many Requests",
	QxEngineStatusRequestHeaderFieldsTooLarge:   "Request Header Fields Too Large",
	QxEngineStatusUnavailableForLegalReasons:    "Unavailable For Legal Reasons",
	QxEngineStatusAccountOrPasswordInvalid:      "account or password invalid",
	QxEngineStatusInternalServerError:           "Internal Server Error",
	QxEngineStatusNotImplemented:                "Not Implemented",
	QxEngineStatusBadGateway:                    "Bad Gateway",
	QxEngineStatusServiceUnavailable:            "Service Unavailable",
	QxEngineStatusGatewayTimeout:                "Gateway Timeout",
	QxEngineStatusHTTPVersionNotSupported:       "HTTP Version Not Supported",
	QxEngineStatusVariantAlsoNegotiates:         "Variant Also Negotiates",
	QxEngineStatusInsufficientStorage:           "Insufficient Storage",
	QxEngineStatusLoopDetected:                  "Loop Detected",
	QxEngineStatusNotExtended:                   "Not Extended",
	QxEngineStatusNetworkAuthenticationRequired: "Network Authentication Required",
}
